// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4678.Shooter1.subsystems;

import org.usfirst.frc4678.Shooter1.RobotMap;
import org.usfirst.frc4678.Shooter1.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {
	double wheelPower = 0;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon shooter = RobotMap.shooterShooter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void setShooterWheel() {
    	//shooter.setPID(0.0005, 0.0001, 0.001);
    	//shooter.setPID(p, i, d, f, izone, closeLoopRampRate, profile);
    	//shooter.setPID(0.2, 0.001, 0.01);
    	shooter.setPID(0.1, 0.0001, 0.001);
    	shooter.changeControlMode(TalonControlMode.Speed);
    	shooter.set(-wheelPower);
    }
    public void setShooterPower(double power) {
    	wheelPower = power;
    }
    public double getShooterPower() {
    	return wheelPower;
    	
    }
}

